### ISSUE TITLE
Complete README.md

### ISSUE THREAD

**Issue by DylanCas** [josht-dev/trail-planner#31]
Create readme file with description, usage notes, screenshot, credits to data sources, and link to deployed application, with additional notes on future development tasks

**Comment by josht-dev** [comment]
Can you add my use of the geoapify autocomplete tutorial to the Credits section of the README? 
Link to the tutorial: https://www.geoapify.com/tutorial/address-input-for-address-validation-and-address-verification-forms-tutorial

**Comment by DylanCas** [comment]
Youtube data api homepage link: https://developers.google.com/youtube/v3
** For the read me section
