### ISSUE TITLE
WIreframe project

### ISSUE THREAD

**Issue by DylanCas** [josht-dev/trail-planner#8]
As a developer on a group project, we wll want a wireframed idea of how we want this webapp to look before we begin our styling coding. 

It is complete when the group has a wire frame image to base our styling coding upon

**Comment by ArticFox04** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/114829265/202596985-47444e0a-db6f-46ef-9796-fa5beea4a220.png)

**Comment by josht-dev** [comment]
Here is a weather card we could use I pulled from my challenge 6. 
![weatherCard](https://user-images.githubusercontent.com/49009098/202603743-3eb4f3f2-440f-4870-8375-e45af6013275.png)

**Comment by ArticFox04** [comment]
![Screenshot_20221117_080000](https://user-images.githubusercontent.com/114829265/202607815-f6ba1c90-5647-4c84-8749-15b8c49d3923.png)
